server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr_management_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always