server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr_management_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

jwt:
  secret: hrmanagementapplicationbynipunsathsara@icetin20250429
  expiration: 86400000

app:
  admin:
    username: admin
    password: admin123

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true